// let a = [1,2,3,4,5,6,7];
// let b = a.slice(0,a.length);
// let c = b.splice(0,2);
// let d = c.shift();
// let e = c.unshift(1,1);
// console.log(a);
// console.log(b);
// console.log(c);
// console.log(d);
let dni = "";